# Generated by Django 4.0.4 on 2022-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancerequests',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Request'),
        ),
        migrations.AlterField(
            model_name='clearancerequests',
            name='status',
            field=models.IntegerField(choices=[(0, 'Submitted'), (1, 'Review'), (2, 'Cleared')], default=1, verbose_name='Status'),
        ),
    ]
