# Generated by Django 4.0.4 on 2022-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0002_alter_clearancerequests_requested_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlnumbers',
            name='control_no',
            field=models.CharField(max_length=14, unique=True, verbose_name='Control Number'),
        ),
        migrations.AlterField(
            model_name='controlnumbers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Student'),
        ),
    ]
