# Generated by Django 4.0.4 on 2022-05-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0003_alter_controlnumbers_control_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlnumbers',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='clearance.clearancerequests'),
        ),
    ]
