# Generated by Django 4.0.4 on 2022-05-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registrar_id',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.supervisor'),
        ),
    ]
