# Generated by Django 4.0.4 on 2022-05-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('dept_hod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.supervisor', verbose_name='HOD')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='StudentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_created=True, verbose_name='Borrowed On')),
                ('return_date', models.DateField(null=True, verbose_name='Returned On')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
                ('student_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.items')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Items',
            field=models.ManyToManyField(related_name='student_items', through='department.StudentItems', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='items',
            name='item_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department', verbose_name='Department'),
        ),
    ]
