# Generated by Django 4.0.4 on 2022-05-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentitems',
            options={'verbose_name': 'Student Item', 'verbose_name_plural': 'Student Items'},
        ),
    ]
