# Generated by Django 4.0.4 on 2022-05-31 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_studentitems_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentitems',
            name='borrow_date',
            field=models.DateField(auto_now_add=True, verbose_name='Borrowed On'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('years', models.IntegerField(verbose_name='Years of Study')),
                ('course_dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.department')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
            },
        ),
    ]
