# Generated by Django 4.0.4 on 2022-05-31 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_registrar_id_student_sponsor_id'),
        ('department', '0004_alter_studentitems_borrow_date_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Createdd On')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='department.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Course',
                'verbose_name_plural': 'Student Courses',
                'db_table': 'student_courses',
            },
        ),
    ]
