# Generated by Django 4.0.4 on 2022-05-31 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_student_course'),
        ('department', '0005_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.student'),
        ),
    ]
