# Generated by Django 4.0.4 on 2022-05-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_studentcourse_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_academic',
            field=models.BooleanField(default=False, verbose_name='Is Academic'),
        ),
    ]
