# Generated by Django 4.0.4 on 2022-06-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(default='mail@mail.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
